variable "project_name" {}
variable "env" {}
variable "db_subnet_group_name" {}
variable "vpc_security_group_ids" {}
variable "engine_version" {}
variable "engine_mode" {}
variable "iops" {}
variable "database_name" {}
variable "master_username" {}
variable "backup_retention_period" {}
variable "skip_final_snapshot" {}
variable "deletion_protection" {}
variable "apply_immediately" {}
variable "min_capacity" {}
variable "max_capacity" {}
variable "subnet_zone_id" {}
variable "performance_insights_enabled" {}
variable "logs_retention_in_days" {}
