variable "vpc_id" {}
variable "env" {}
variable "project_name" {}
variable "alb_private_subnet_a_id" {}
variable "alb_private_subnet_c_id" {}
variable "alb_private_subnet_d_id" {}
variable "ecs_private_subnet_a_id" {}
variable "ecs_private_subnet_c_id" {}
variable "ecs_private_subnet_d_id" {}
